### ISSUE TITLE
Wrapper for embedded board

### ISSUE THREAD

**Issue by Prathik4** [richard-damon/FreeRTOScpp#1]
Hello,
I was just wondering if this wrapper can be used with raspberry pi 2 board?
I'm working on a small bare metal project written in c++ ,where I want to run the tasks in real time on the pi board.

Thanks you.

**Comment by richard-damon** [comment]
FreeeRTOS is a microkernal that can be compiled into a program . As such,  you should be able to write a program for the Pi, but you would configure the system to boot into that program instead of the normal Linux kernel., which is probably not what you are thinking

**Comment by Prathik4** [comment]
Thanks for the quick reply.. 👍
