### ISSUE TITLE
Proprietary license on some files

### ISSUE THREAD

**Issue by andysifferman** [richard-damon/FreeRTOScpp#4]
The header at the top of files Lock.cpp and Lock.h contain a copyright notice that is incompatible with the MIT license claimed by the author. The text reads:

```
...
   Copyright (c) 2017. Optics 1, Inc. All Rights Reserved.
 * Permission to use, copy, modify, and distribute this software and
 * its documentation for any purpose, without fee and without a signed
 * licensing agreement, is hereby prohibited. Any unauthorized
 * reproduction or distribution of this software, or any portion of it,
 * may result in severe civil and criminal penalties, and will be
 * prosecuted to the maximum extent possible under the law.
...
```
This brings into question the legitimacy of releasing under the MIT license _any_ of the files provided in the FreeRTOS library. Is Optics 1, Inc. the rightful owner of all of the intellectual property in this library?

**Comment by richard-damon** [comment]
Fixed Header Copyright. I have permission from my employer, Optics 1, to release this code, which I personally wrote, as open source. The previous comment was added in error as the default on the machine I used to create that additional component to the library.
