### ISSUE TITLE
Timer pointer to member function not correct

### ISSUE THREAD

**Issue by jcforlc** [richard-damon/FreeRTOScpp#6]
Perhaps I am, missing something but I think the following  member function call is incorrect:

virtual void timer() {(obj->func)();}

should be:
virtual void timer() {(obj->*func)();}

Which allows a unique timer handler function for each timer member.

**Comment by richard-damon** [comment]
Yes, I think you are correct there. I mostly use the TimerClass version so this version isn't as well tested. Will try to get that rolled into an update soon.

**Comment by richard-damon** [comment]
Committed fix with the change.
